### ISSUE TITLE
reg and vib

### ISSUE THREAD

**Issue by lyufan** [AlanPeng0897/Defend_MI#5]
Can you explain what the reg and vib in the defends parameter means, thank you!
<img width="602" alt="image" src="https://user-images.githubusercontent.com/33341810/218234194-6b97c67b-e09e-47a1-ab37-524a01bdfa71.png">

**Comment by AlanPeng0897** [comment]
"reg" denotes "regular model" with no defense, "vib" denotes the baseline.

**Comment by lyufan** [comment]
Thanks!
